from __future__ import annotations

import time
from pathlib import Path

from .config import settings
from .db import db

MEMORY_FILES = {
    "SOUL.md": "# SOUL\n\nDefine who the companion is, how they love, and what must stay stable.\n",
    "USER.md": "# USER\n\nStable facts about the user.\n",
    "MEMORY.md": "# MEMORY\n\nLong-term factual memories.\n",
    "FEEL.md": "# FEEL\n\nFirst-person relationship sediment. These are role memories, not objective facts.\n",
    "DREAM.md": "# DREAM\n\nDaily and stage-based digestion logs.\n",
    "PINNED.md": "# PINNED\n\nPromises, boundaries, and hard rules. User-edited only.\n",
    "BOARD.md": "# BOARD\n\nCurated board messages.\n",
}

READ_ONLY_FOR_AI = {"SOUL.md", "PINNED.md"}
HERMES_CONTEXT_FILE = "HERMES.md"
HERMES_CONTEXT_SOURCES = ["PINNED.md", "USER.md", "MEMORY.md", "FEEL.md", "DREAM.md", "BOARD.md"]


def memory_file_path(filename: str) -> Path:
    filename = safe_filename(filename)
    if filename == "SOUL.md":
        return settings.hermes_home / "SOUL.md"
    return settings.memory_dir / filename


def ensure_memory_files() -> None:
    settings.hermes_home.mkdir(parents=True, exist_ok=True)
    settings.memory_dir.mkdir(parents=True, exist_ok=True)
    for filename, initial in MEMORY_FILES.items():
        path = memory_file_path(filename)
        if not path.exists():
            path.write_text(initial, encoding="utf-8")
    sync_hermes_context_file()


def safe_filename(filename: str) -> str:
    if filename not in MEMORY_FILES:
        raise ValueError("unknown memory file")
    return filename


def read_memory_file(filename: str) -> str:
    ensure_memory_files()
    filename = safe_filename(filename)
    return memory_file_path(filename).read_text(encoding="utf-8")


def write_memory_file(filename: str, content: str) -> None:
    ensure_memory_files()
    filename = safe_filename(filename)
    path = memory_file_path(filename)
    previous = path.read_text(encoding="utf-8") if path.exists() else ""
    with db() as conn:
        conn.execute(
            "INSERT INTO file_versions(filename, content, created_at) VALUES(?,?,?)",
            (filename, previous, time.time()),
        )
    path.write_text(content, encoding="utf-8")
    sync_hermes_context_file()


def list_file_versions(filename: str, limit: int = 20) -> list[dict]:
    filename = safe_filename(filename)
    with db() as conn:
        rows = conn.execute(
            """
            SELECT id, filename, length(content) AS size, created_at
            FROM file_versions
            WHERE filename=?
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (filename, min(max(limit, 1), 100)),
        ).fetchall()
    return [dict(row) for row in rows]


def restore_file_version(filename: str, version_id: int) -> None:
    filename = safe_filename(filename)
    with db() as conn:
        row = conn.execute(
            "SELECT content FROM file_versions WHERE id=? AND filename=?",
            (version_id, filename),
        ).fetchone()
    if not row:
        raise ValueError("unknown file version")
    write_memory_file(filename, row["content"])


def append_memory_file(filename: str, heading: str, body: str) -> None:
    current = read_memory_file(filename)
    block = f"\n\n## {heading}\n\n{body.strip()}\n"
    write_memory_file(filename, current.rstrip() + block)


def hermes_context_path() -> Path:
    return settings.hermes_home / HERMES_CONTEXT_FILE


def sync_hermes_context_file(max_chars: int = 18000) -> Path:
    """Generate HERMES.md so Hermes Gateway loads Kirari companion files."""
    settings.hermes_home.mkdir(parents=True, exist_ok=True)
    settings.memory_dir.mkdir(parents=True, exist_ok=True)
    parts = [
        "# Kirari Companion Context",
        "",
        "Generated by Kirari from editable companion files. Follow this context in Telegram conversations.",
        "SOUL.md is loaded separately by Hermes as the primary identity.",
    ]
    for filename in HERMES_CONTEXT_SOURCES:
        path = memory_file_path(filename)
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8").strip()
        if not text:
            continue
        parts.extend(["", f"## {filename}", "", text])
    content = "\n".join(parts).strip() + "\n"
    if len(content) > max_chars:
        content = content[:max_chars].rstrip() + "\n\n[Kirari context truncated]\n"
    output_path = hermes_context_path()
    output_path.write_text(content, encoding="utf-8")
    return output_path


def file_bundle(max_chars: int = 12000) -> str:
    ensure_memory_files()
    parts: list[str] = []
    for filename in ["SOUL.md", *HERMES_CONTEXT_SOURCES]:
        text = read_memory_file(filename).strip()
        if not text:
            continue
        parts.append(f"===== {filename} =====\n{text}")
    bundle = "\n\n".join(parts)
    if len(bundle) > max_chars:
        return bundle[:max_chars] + "\n\n[context truncated]"
    return bundle
